version: '3.8'
services:
  mongo:
    image: mongo:6.0.6
    restart: always
    hostname: mongo1
    expose:
      - 27017
    ports:
      - "27017:27017"

#  mongoinit:
#    image: mongo
#    # this container will exit after executing the command
#    restart: "no"
#    depends_on:
#      - mongo
#    command: >
#      mongo --host mongo1:27017 --eval
#      '
#      db = (new Mongo("localhost:27017")).getDB("test");
#      config = {
#      "_id" : "my-mongo-set",
#      "members" : [
#        {
#          "_id" : 0,
#          "host" : "mongo1:27017"
#        }
#      ]
#      };
#      rs.initiate(config);
#      '
#

  kafka:
    image: confluentinc/cp-kafka:7.2.2
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
