version: '3.8'
services:
  mongo:
    image: mongo:6.0.6
    restart: always
    hostname: mongo
    ports:
      - "27017:27017"

  utility:
    depends_on: [mongo]
    build:
      context: ../..
      dockerfile: Dockerfile
    hostname: utility
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017


#  kafka:
#    image: confluentinc/cp-kafka:7.2.2
#    ports:
#      - "9092:9092"
#    environment:
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#    depends_on:
#      - zookeeper
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      - ZOOKEEPER_CLIENT_PORT=2181
#      - ZOOKEEPER_TICK_TIME=2000
#
#  user-event-builder:
#    depends_on:
#      - mongo
#      - kafka
#    image: gridql/mongo-event-builder
#    volumes:
#      - ./event_builders/user/:/app/config/
