"user": {
  "uri": "mongodb://host.docker.internal:27017/?replicaSet=rs0",
  "collection": "user",
  "db": "customer_prod"
},
"billing_account": {
  "uri": "mongodb://host.docker.internal:27017/?replicaSet=rs0",
  "collection": "billing_account",
  "db": "customer_prod"
}
