apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

configMapGenerator:
  - name: env-conf
    files:
      - env.conf

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: utilityapi
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: utilityapi
              volumeMounts:
              - mountPath: /app/config/environment
                name: environment
              env: ${{ env.MONGO_CONNECTION_STRING }}
          volumes:
          - name: environment
            configMap: 
              name: env-conf
