apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

configMapGenerator:
- files:
  - env.conf
  name: env-conf

patches:
- patch: |-
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: utilityapi
   spec:
     replicas: 1
     template:
        spec:
         containers:
           - name: utilityapi
             image: tsmarsh/utilityapi:5448407502
             volumeMounts:
             - mountPath: /app/config/environment
               name: environment
  
             env:
                - name: MONGO_CONNECTION_STRING
                  valueFrom:
                    secretKeyRef:
                       name: mongo-connection-string
                       key: MONGO_CONNECTION_STRING
         volumes:
           - name: environment
             configMap:
                name: env-conf

- patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: mongo-connection-string
    data:
      MONGO_CONNECTION_STRING: bW9uZ29kYitzcnY6Ly9ncmlkcWw6VGlsZGFyYzE0MTRAZGV2LmFpd2ljenQubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==