apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: utilityapi
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: utilityapi
              image: tsmarsh/utilityapi:dev