name: Build and Push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/bounded_contexts/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/bounded_contexts
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/utilityapi:latest
