# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install
    - run: yarn test

  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/bounded_contexts
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/utilityapi:${{ github.run_id }}

      - name: Update Terraform Configuration
        run: |
          sed -i "s|${{ secrets.DOCKERHUB_USER }}/utilityapi:.*|${{ secrets.DOCKERHUB_USER }}/utilityapi:${{ github.run_id }}\"|" main.tf
        working-directory: ./iac/environments/dev

      - name: Commit Terraform Changes
        run: |
          git config --global user.name 'UtilityHelper Docker Build'
          git config --global user.email 'uh.build@tailoredshapes.com'
          git add ./iac/environments/dev/main.tf
          git commit -m "Update Docker image tag in Terraform to ${{ github.run_id }}"
          git push
